language: C++



compiler:
       - gcc
       - clang
       - wget https://github.com/Akheon23/libsuinput ./


before_install: sudo hostname 10.0.0.2 && sudo apt-get -y --force-yes -f install cmake  && ./cmake ./ && ./configure && make

install: true
