language: C++



compiler:
       - gcc
       - cmake
       - git clone https://github.com/Akheon23/libsuinput --version=2.8.2


before_install: apt-get install cmake git 
./cmake && ./autogen.sh
install: true
